// <auto-generated />
using System;
using MenuService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MenuService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MenuDbContext))]
    partial class MenuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MenuService.Domain.Models.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ch1");

                    b.Property<string>("AppAdminReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cf6");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cf4");

                    b.Property<bool>("IsActif")
                        .HasColumnType("boolean")
                        .HasColumnName("cf5");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cf1");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cf2");

                    b.Property<string>("UrlFront")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cf3");

                    b.HasKey("Id");

                    b.ToTable("TM00001");
                });
#pragma warning restore 612, 618
        }
    }
}
