// <auto-generated />
using System;
using MagasinService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MagasinService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MagasinServiceDbContext))]
    [Migration("20251204092753_AddStockMovementFeatures")]
    partial class AddStockMovementFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MagasinService.Domain.Entities.StockLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ch1");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StockLocations");
                });

            modelBuilder.Entity("MagasinService.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ch1");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationLocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SourceLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("Reference");

                    b.HasIndex("SourceLocationId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("MagasinService.Domain.Entities.StockSlip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ch1");

                    b.Property<Guid>("BoutiqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DestinationLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SlipType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BoutiqueId");

                    b.HasIndex("Date");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("SourceLocationId");

                    b.ToTable("StockSlips");
                });

            modelBuilder.Entity("MagasinService.Domain.Entities.StockSlipItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ch1");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockSlipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StockSlipId", "ProductId");

                    b.ToTable("StockSlipItems");
                });

            modelBuilder.Entity("MagasinService.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("MagasinService.Domain.Entities.StockLocation", "DestinationLocation")
                        .WithMany("DestinationMovements")
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagasinService.Domain.Entities.StockLocation", "SourceLocation")
                        .WithMany("SourceMovements")
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationLocation");

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("MagasinService.Domain.Entities.StockSlip", b =>
                {
                    b.HasOne("MagasinService.Domain.Entities.StockLocation", "DestinationLocation")
                        .WithMany("DestinationSlips")
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MagasinService.Domain.Entities.StockLocation", "SourceLocation")
                        .WithMany("SourceSlips")
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationLocation");

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("MagasinService.Domain.Entities.StockSlipItem", b =>
                {
                    b.HasOne("MagasinService.Domain.Entities.StockSlip", "StockSlip")
                        .WithMany("StockSlipItems")
                        .HasForeignKey("StockSlipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockSlip");
                });

            modelBuilder.Entity("MagasinService.Domain.Entities.StockLocation", b =>
                {
                    b.Navigation("DestinationMovements");

                    b.Navigation("DestinationSlips");

                    b.Navigation("SourceMovements");

                    b.Navigation("SourceSlips");
                });

            modelBuilder.Entity("MagasinService.Domain.Entities.StockSlip", b =>
                {
                    b.Navigation("StockSlipItems");
                });
#pragma warning restore 612, 618
        }
    }
}
