// <auto-generated />
using System;
using Menu.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Menu.Grpc.Migrations
{
    [DbContext(typeof(MenuContext))]
    [Migration("20251110194937_InitMenuId")]
    partial class InitMenuId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Menu.Grpc.Models.MenuNav", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ch1");

                    b.Property<string>("ApiRoute")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cf2");

                    b.Property<Guid>("AppAdminId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cf5");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cf4");

                    b.Property<bool>("IsActif")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cf6");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cf1");

                    b.Property<string>("UrlFront")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cf3");

                    b.HasKey("Id");

                    b.ToTable("TM00001");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1cb25cbe-1f2f-4fc8-bf53-25255dbd9b68"),
                            ApiRoute = "/product",
                            AppAdminId = new Guid("b9bd41f4-cb78-4d71-b2a2-08d385944f15"),
                            Icon = "fa-solid fa-bag-shopping",
                            IsActif = true,
                            Name = "Produit",
                            UrlFront = "/produit"
                        },
                        new
                        {
                            Id = new Guid("5d5b22a1-dc69-4b66-811a-9b4598b71f00"),
                            ApiRoute = "/sale",
                            AppAdminId = new Guid("2c252630-2e4f-4d09-b2d6-057e4f04eff1"),
                            Icon = "fa-solid fa-chart-pie",
                            IsActif = true,
                            Name = "Tableau de bord",
                            UrlFront = "/dashboard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
