// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TresorerieService.Infrastructure.Data;

#nullable disable

namespace TresorerieService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TresorerieDbContext))]
    [Migration("20251214020633_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TresorerieService.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ch1");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("fld5");

                    b.Property<decimal?>("AlertThreshold")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("fld13");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fld1");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fld6");

                    b.Property<string>("BoutiqueId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fld2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ch2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ch4");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("fld9");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("fld8");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fld14");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("fld7");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("fld10");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("fld11");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fld3");

                    b.Property<decimal?>("OverdraftLimit")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("fld12");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("fld4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ch3");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ch5");

                    b.HasKey("Id");

                    b.ToTable("TA00001");
                });

            modelBuilder.Entity("TresorerieService.Domain.Entities.CashFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("fld12");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("fld8");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fld1");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text")
                        .HasColumnName("fld31");

                    b.Property<bool>("AutoApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("fld35");

                    b.Property<string>("BankStatementReference")
                        .HasColumnType("text")
                        .HasColumnName("fld28");

                    b.Property<string>("BoutiqueId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fld2");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fld5");

                    b.Property<Guid>("CategoryId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ch2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ch4");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fld11");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fld15");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("fld7");

                    b.Property<Guid?>("DestinationAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("fld13");

                    b.Property<bool>("IsReconciled")
                        .HasColumnType("boolean")
                        .HasColumnName("fld25");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("fld29");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("fld34");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fld6");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fld14");

                    b.Property<DateTime?>("ReconciledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fld26");

                    b.Property<string>("ReconciledBy")
                        .HasColumnType("text")
                        .HasColumnName("fld27");

                    b.Property<string>("RecurringCashFlowId")
                        .HasColumnType("text")
                        .HasColumnName("fld30");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("fld3");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("fld24");

                    b.Property<string>("RelatedId")
                        .HasColumnType("text")
                        .HasColumnName("fld33");

                    b.Property<string>("RelatedType")
                        .HasColumnType("text")
                        .HasColumnName("fld32");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("fld19");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fld20");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("text")
                        .HasColumnName("fld21");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("fld9");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("fld10");

                    b.Property<string>("ThirdPartyId")
                        .HasColumnType("text")
                        .HasColumnName("fld18");

                    b.Property<string>("ThirdPartyName")
                        .HasColumnType("text")
                        .HasColumnName("fld17");

                    b.Property<int?>("ThirdPartyType")
                        .HasColumnType("integer")
                        .HasColumnName("fld16");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("fld4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ch3");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ch5");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fld22");

                    b.Property<string>("ValidatedBy")
                        .HasColumnType("text")
                        .HasColumnName("fld23");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId1");

                    b.HasIndex("DestinationAccountId");

                    b.ToTable("TC00001");
                });

            modelBuilder.Entity("TresorerieService.Domain.Entities.CashFlowHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ch1");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("fld2");

                    b.Property<string>("CashFlowId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fld1");

                    b.Property<Guid>("CashFlowId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("fld25");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ch2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ch4");

                    b.Property<string>("NewStatus")
                        .HasColumnType("text")
                        .HasColumnName("fld4");

                    b.Property<string>("OldStatus")
                        .HasColumnType("text")
                        .HasColumnName("fld3");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ch3");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ch5");

                    b.HasKey("Id");

                    b.HasIndex("CashFlowId1");

                    b.ToTable("TC00002");
                });

            modelBuilder.Entity("TresorerieService.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ch1");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fld1");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ch2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ch4");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fld4");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("fld5");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fld2");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("fld3");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ch3");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ch5");

                    b.HasKey("Id");

                    b.ToTable("TC00003");
                });

            modelBuilder.Entity("TresorerieService.Domain.Entities.CashFlow", b =>
                {
                    b.HasOne("TresorerieService.Domain.Entities.Account", "Account")
                        .WithMany("CashFlows")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TresorerieService.Domain.Entities.Category", "Category")
                        .WithMany("CashFlows")
                        .HasForeignKey("CategoryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TresorerieService.Domain.Entities.Account", "DestinationAccount")
                        .WithMany("DestinationCashFlows")
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("DestinationAccount");
                });

            modelBuilder.Entity("TresorerieService.Domain.Entities.CashFlowHistory", b =>
                {
                    b.HasOne("TresorerieService.Domain.Entities.CashFlow", "CashFlow")
                        .WithMany("History")
                        .HasForeignKey("CashFlowId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashFlow");
                });

            modelBuilder.Entity("TresorerieService.Domain.Entities.Account", b =>
                {
                    b.Navigation("CashFlows");

                    b.Navigation("DestinationCashFlows");
                });

            modelBuilder.Entity("TresorerieService.Domain.Entities.CashFlow", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("TresorerieService.Domain.Entities.Category", b =>
                {
                    b.Navigation("CashFlows");
                });
#pragma warning restore 612, 618
        }
    }
}
