global using IDR.Library.BuildingBlocks.Behaviors;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using MagasinService.Domain.Entities;
global using Microsoft.EntityFrameworkCore;
global using IDR.Library.BuildingBlocks.CQRS;
global using IDR.Library.BuildingBlocks.Repositories;
global using Mapster;